### ISSUE TITLE
Nissan Altima

### ISSUE THREAD

**Issue by kellcomnet2** [dan-r/HomeAssistant-NissanConnect#66]
**Is your feature request related to a problem? Please describe.**
Listing this as a feature request instead of as a bug as the Nissan Altima is not one of the listed supported vehicles. However, I have a 2021 Altima and a NissanConnect account but when attempting to add the integration I am presented with "Unknown error occurred"

**Describe the solution you'd like**
I would love automatic odometer tracking in HASS

**Describe alternatives you've considered**
An OBD2 reader that transmits to HASS

**Additional context**

Logs show

'''
  File "/config/custom_components/nissan_connect/config_flow.py", line 39, in async_step_user
    kamereon_session = NCISession(
                       ^^^^^^^^^^^
  File "/config/custom_components/nissan_connect/kamereon.py", line 610, in __init__
    self.settings = settings_map[self.tenant][region]
                    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'US'

'''

**Comment by dan-r** [comment]
This integration currently doesn't support NissanConnect in North America, there's a note about why on the README under vehicle support (The EU/US selection on the setup page does need updating, although I've been putting this off because support for Japan is being worked on). 

Currently only European accounts are supported, and the Altima isn't sold in Europe. If you or someone else from the US wants to work on support, that would be great, but it's not something I'm able to implement.

**Comment by kellcomnet2** [comment]
Thank you for your consice response. I'm good with closing this request. After reading the issues with the NA API I fully understand.

**Comment by dan-r** [comment]
I remain hopeful that one day I'll be able to support NA, but will close this for now. Thanks for your interest regardless!

Dan
